#!/usr/bin/env bash
# PreToolUse (Write|Edit) hook for the NightOwl web SPA.
# The route map + route() helper are a target convention (see .claude/rules/routes.md)
# generated by the api's future `composer routes:export` — not built yet, so this only
# fires if/once those files exist. Non-blocking reminder: emits additionalContext. Exits 0.
set -euo pipefail

input="$(cat)"
file="$(printf '%s' "$input" | jq -r '.tool_input.file_path // empty')"
[ -z "$file" ] && exit 0

case "$file" in
  */src/lib/routes.js|*/src/lib/routes.d.ts) ;;
  *) exit 0 ;;
esac

msg="REMINDER: this file is GENERATED by the api's 'composer routes:export' — do not hand-edit it. Routes are api-owned: change api/routes/api.php (or the module's Routes/api.php), then re-run the export."
jq -cn --arg m "$msg" '{hookSpecificOutput:{hookEventName:"PreToolUse",additionalContext:$m}}'
exit 0
